# Fabric Loom / Minecraft properties
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT
fabric_api_version=0.155.3+26.1.2
modmenu_version=18.0.0-beta.1

# Java 25 is required by Minecraft 26.1+
java_version=25

# Mod properties
mod_version=0.4.0-strip
maven_group=com.hapnoid
archives_base_name=autohotbar-remake

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
